### PR TITLE
Scaling and support for the 1.54 inch

### PR DESCRIPTION
**Pull request by thilohille**
Yes, there is a nasty fix_framebuffer_MVLSB in fbdrawing which will be removed once i find a better place for it. Also i replaced the buffer-manipulation in set/get_absolute_pixel with calls to the framebuf.pixel method.

### CODE REVIEW

**Comment by chevdor** [comment]
Many thanks for the PR @thilohille.
I did a quick check and the changes seem to introduce a regression.

I need to look into the details unless you have an idea.
When running my test_4()-5()-6() in `ws2in9b_0.py`, the drawing of the pixels fails, or at least the pixels don´t land at the right location.

The tests 1-2-3 do pass and they do not test pixel drawing (only rectangles and fb text). 
Test 4-5-6 do use `set_absolute_pixel` and `set_pixel`. 
If those tests fail, the rest will also fail.

**Comment by thilohille** [comment]
@chevdor: please give this a try.
I could not test it but it should be your working setup plus scaling.

**Comment by thilohille** [comment]
@chevdor ok, this one SHOULD work. 
Also i added a scroll method to fbdrawing. You can check test6() in samples/ws1in54_font.py how set_scale and scroll works.
If you do not see anything try inverting the colored variable in set_absolute_pixel. (this is what i have to get pixels drawn)

**Comment by chevdor** [comment]
Sorry it took so long. I cannot test atm and I am not activeley working in the repo but *I take it* :)

**Pull request merged**
